#!/usr/bin/env bash
# Generate THIRD_PARTY.md — the attribution notice that must ship with the
# binary (FRD-020 §9.2).
#
# budctl is statically linked: client-go, Helm, SOPS and age are compiled in,
# not called as processes. Handing someone the binary therefore redistributes
# all of their code, and Apache-2.0 §4, MIT, BSD and MPL-2.0 each require their
# notices to travel with it. This produces one file carrying the module list and
# the full text of every distinct licence, deduplicated by content — sixty
# modules under Apache-2.0 share one text, but a module that appended its own
# copyright line gets its own entry.
set -euo pipefail

cd "$(dirname "$0")"
OUT="${OUT:-THIRD_PARTY.md}"
SELF="github.com/BudEcosystem/budctl"

if ! command -v go-licenses >/dev/null 2>&1; then
  echo "go-licenses is required: go install github.com/google/go-licenses@v1.6.0" >&2
  exit 1
fi

tmp="$(mktemp -d)"
trap 'rm -rf "$tmp"' EXIT

# save writes each module's licence file; csv gives the module -> licence/url
# mapping. Both walk the same graph, so they agree on what is linked in.
go-licenses save ./cmd/budctl --save_path="$tmp/lic" --force 2>"$tmp/save.err" || {
  echo "go-licenses save failed:" >&2; tail -20 "$tmp/save.err" >&2; exit 1; }
go-licenses csv ./cmd/budctl 2>/dev/null | grep -v "^${SELF}" | sort > "$tmp/deps.csv"

count=$(grep -c . "$tmp/deps.csv")
[ "$count" -gt 50 ] || { echo "only $count dependencies found; the graph walk failed" >&2; exit 1; }

{
  echo "# Third-party software in budctl"
  echo
  echo "budctl ships as a statically linked binary, so the modules below are compiled"
  echo "into every copy of it. This file carries their licences, as those licences require."
  echo
  echo "Generated by \`third-party.sh\`. Do not edit by hand."
  echo
  echo "## Modules"
  echo
  echo "| Module | Licence | Source |"
  echo "|---|---|---|"
  while IFS=, read -r mod url lic; do
    echo "| \`$mod\` | $lic | $url |"
  done < "$tmp/deps.csv"
  echo
  echo "## Licence texts"
  echo
} > "$OUT"

# Group modules by the exact bytes of their licence file.
declare -A bymod
while IFS=, read -r mod url lic; do bymod["$mod"]="$lic"; done < "$tmp/deps.csv"

declare -A seen
while IFS= read -r f; do
  mod="${f#"$tmp/lic/"}"; mod="$(dirname "$mod")"
  case "$mod" in "$SELF"*) continue;; esac
  h="$(sha256sum "$f" | cut -c1-16)"
  if [ -n "${seen[$h]:-}" ]; then
    seen[$h]="${seen[$h]}|$mod"
  else
    seen[$h]="$mod"
    printf '%s\n' "$h" >> "$tmp/order"
  fi
  printf '%s\t%s\n' "$h" "$f" >> "$tmp/files"
# `save` copies the whole source tree of MPL-licensed modules, because MPL
# requires source availability. Only the licence files themselves belong here.
done < <(find "$tmp/lic" -type f -iregex '.*/\(LICEN[SC]E\|COPYING\|NOTICE\)[^/]*' | sort)

while IFS= read -r h; do
  mods="${seen[$h]}"
  first="${mods%%|*}"
  n=$(printf '%s' "$mods" | tr '|' '\n' | grep -c .)
  # awk exits on its own; `| head -1` would SIGPIPE the reader and, under
  # pipefail, abort the script mid-file.
  file="$(awk -F'\t' -v h="$h" '$1 == h { print $2; exit }' "$tmp/files")"
  {
    if [ "$n" -gt 1 ]; then
      echo "### ${bymod[$first]:-Licence} — $first and $((n - 1)) other module(s)"
      echo
      echo "<details><summary>Modules sharing this text</summary>"
      echo
      printf '%s' "$mods" | tr '|' '\n' | sed 's/^/- `/; s/$/`/'
      echo
      echo "</details>"
    else
      echo "### ${bymod[$first]:-Licence} — $first"
    fi
    echo
    echo '```'
    cat "$file"
    echo '```'
    echo
  } >> "$OUT"
done < "$tmp/order"

echo "wrote $OUT: $count modules, $(grep -c . "$tmp/order") distinct licence texts, $(wc -c < "$OUT") bytes"
